name: my-package-name

dependencies:
  - base == 4.*
  - containers
  - haskell-say

executables:
  my-package-name:
    main: Main.hs
    source-dirs:
      - src
      - app

tests:
  haskell-hello-spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec == 2.*
    build-tools: hspec-discover

